### ISSUE TITLE
Quad Alg Rhythm 1.0

### ISSUE THREAD

**Issue by midiguru** [almostEric/FrozenWasteland#36]
A couple of minor issues in Quad Algorithmic Rhythm (which is a terrific device, by the way). At present it continues moving even if the clock input is not receiving trigger signals. If I clock it from Impromptu Clocked, for example, when I stop Clocked, QAR keeps right on running. It only stops when there is no cable connected to the clock input jack.

The button next to the Mute jack doesn't work. I can connect an external gate to the Mute input jack to shut it off, but this isn't convenient. Rather than a Mute input, a Run input would be much better, as that could be linked directly to Clocked.

**Comment by almostEric** [comment]
Hi, I'll take a look at the clock, but not sure it is possible. There is no way of knowing if Clocked is in run mode or not - I am just waiting for the next trigger to determine the speed, so there is no way for me to know that another trigger is not coming - it might just be a *really* slow BPM. I might be able to add a Halt input that you could use to stop it.

Right now, it is just a light next to the Mute jack, not a button so that is why clicking on it didn't do anything. But I was planning on turning it into a button as well. :)

Next version should be released soon, with a new Algorithm - Boolean Logic. In this mode, tracks 3 & 4 can perform logical operations on the two previous tracks (so track 3 combines 1 & 2, 4 combines 2 & 3). The Division control chooses the operation, right now I have AND, OR, XOR and NOR. In this mode these tracks still have their own offset, accents and with the QRE, probability and swing. It's pretty cool!

**Comment by WouterSpekkink** [comment]
Sorry for commenting on an issue that you closed, but I was going to report the issue mentioned in the first paragraph. If I connect a clock to the clock input (I tried two different clocks as inputs and the problem occurs with both) and then stop the clock, the quad algorithmic rhythm will continue to run very slowly.

**Comment by almostEric** [comment]
As discussed this is the nature of the way clock division works

**Comment by WouterSpekkink** [comment]
Ah, okay. Sorry, I did not fully understand the explanation before, but after rereading it a couple of times I think I get it. So, if I can make a suggestion: Rather than using a Halt input, why not just use a Run input that makes sure that the sequencer only tries to progress when Run is switched on? Most clocks have a run output, but not a halt output.

**Comment by almostEric** [comment]
There is no halt/run input - only a Clock Input.

**Comment by WouterSpekkink** [comment]
No, but I was referring to the suggestion that you made in your first reply in this thread (last sentence of the first paragraph).

**Comment by almostEric** [comment]
I'll take a look
