### ISSUE TITLE
Portland Weather - divisions 

### ISSUE THREAD

**Issue by amp3rsand** [almostEric/FrozenWasteland#64]
When changing the divisions parameter I am getting 2 different readings between the display and the tooltip.

When at the bottom of the range the display indicates 'X 24' but the tooltip indicates 'Divisions: 0'. the display indicates 'X 16' the tooltip indicates 'Divisions: 1' and so on...

**Comment by almostEric** [comment]
Hi,

 

Sounds like an off by 1 error in my string look up code. It will be fixed in next update (coming pretty soon)

 

Eric

 

From: amp3rsand 
Sent: Tuesday, June 16, 2020 11:42 PM
To: almostEric/FrozenWasteland <FrozenWasteland@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: [almostEric/FrozenWasteland] Portland Weather - divisions (#64)

 

When changing the divisions parameter I am getting 2 different readings between the display and the tooltip.

When at the bottom of the range the display indicates 'X 24' but the tooltip indicates 'Divisions: 0'. the display indicates 'X 16' the tooltip indicates 'Divisions: 1' and so on...

**Comment by almostEric** [comment]
divisions has been refactored and fixed
