### ISSUE TITLE
Damian Lillard

### ISSUE THREAD

**Issue by philippesalembier** [almostEric/FrozenWasteland#68]
Hi Eric, 

Thank you so much for all your contributions to VCV. It is a real pleasure to use your modules. I have started to experiment with Damian Lillard and it is not working exactly as I was expecting. If no processing blocks are inserted between the sends and returns, I was expecting to get at the output a close copy of the input. However, I see a significant  difference with the default parameters. Moreover, this difference can become very large if the cutoff frequency of band3 is increased. 
Here is a rack showing what I am talking about. 
[Test Daminan Lillard.vcv.zip](https://github.com/almostEric/FrozenWasteland/files/4977851/Test.Daminan.Lillard.vcv.zip)

I know filter design may be tricky;) Please let me know, if you think that there may be an issue with some filters. 

Thanks in advance for your feedback.

**Comment by almostEric** [comment]
Yep

That is entirely possible due to the way filters work – there is always going to be a bit of phase distortion, I have tried to minimize it but with certain cutoff frequencies it gets more pronounced :/

almostEric

From: Philippe Salembier
Sent: Sunday, July 26, 2020 5:34 PM
To: almostEric/FrozenWasteland <FrozenWasteland@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: [almostEric/FrozenWasteland] Damian Lillard (#68)


Hi Eric,

Thank you so much for all your contributions to VCV. It is a real pleasure to use your modules. I have started to experiment with Damian Lillard and it is not working exactly as I was expecting. If no processing blocks are inserted between the sends and returns, I was expecting to get at the output a close copy of the input. However, I see a significant difference with the default parameters. Moreover, this difference can become very large if the cutoff frequency of band3 is increased.
Here is a rack showing what I am talking about.
Test Daminan Lillard.vcv.zip<https://github.com/almostEric/FrozenWasteland/files/4977851/Test.Daminan.Lillard.vcv.zip>

I know filter design may be tricky;) Please let me know, if you think that there may be an issue with some filters.

Thanks in advance for your feedback.

**Comment by philippesalembier** [comment]
Ok. Thanks. Best regards
