### ISSUE TITLE
Megalomaniac Compression "crossover" design problem

### ISSUE THREAD

**Issue by 44100hertz** [almostEric/FrozenWasteland#98]
I have not found it possible to use your multiband compressor plugin.

Multiband compressors generally work this way: You specify the crossover point, and bands are generated using those points by splitting the frequency domain on both sides of the point. Here's some pseudocode for a 2-band compressor:

```js
let cross_point = 200.0
let low_band = lowpass(input, cross_point)
let high_band = input - low_band // this is similar to highpass(input, cross_point)
let output = compress(low_band) + compress(high_band)
```

The spectrum is split up in such a way that when there is no compression active, nothing happens to the output signal. Correct me if I'm wrong, but with megalomaniac, instead of specifying the crossover point, for the center bands, you specify the center point of a bandpass filter with an unspecified width. This makes it impossible for me to use your plugin without destroying the consistency of the frequency domain.

**Comment by almostEric** [comment]
Thank you for explaining to me how multiband compressors work

**Comment by 44100hertz** [comment]
OK so you already know how they are supposed to work, but made it weird on purpose? I guess that leaves the work to me.

**Comment by almostEric** [comment]
Hi Cyan,

There is no *one way* that multiband compressors work. I’m sorry you find mine unusable, I wish you good luck in your quest to find one that meets your needs.

Cheers
almosteric

From: Cyan
Sent: Thursday, October 7, 2021 11:22 PM
To: almostEric/FrozenWasteland ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [almostEric/FrozenWasteland] Megalomaniac Compression "crossover" design problem (#98)


I have not found it possible to use your multiband compressor plugin.

Multiband compressors generally work this way: You specify the crossover point, and bands are generated using those points by splitting the frequency domain on both sides of the point. Here's some pseudocode for a 2-band compressor:

let cross_point = 200.0

let low_band = lowpass(input, cross_point)

let high_band = input - low_band // this is similar to highpass(input, cross_point)

let output = compress(low_band) + compress(high_band)

The spectrum is split up in such a way that when there is no compression active, nothing happens to the output signal. Correct me if I'm wrong, but with megalomaniac, instead of specifying the crossover point, for the center bands, you specify the center point of a bandpass filter with an unspecified width. This makes it impossible for me to use your plugin without destroying the consistency of the frequency domain.
